version: '3'
services:
    auth:
      build: src
      env_file:
        - envs/.env
      depends_on:
        - redis_auth
        - postgres_auth
      volumes:
        - ./src:/auth
      expose:
        - 5000
      ports:
        - 5555:5555

    redis_auth:
      image: redis:7-alpine
      ports:
        - 6379:6379

    postgres_auth:
      image: postgres:13.0-alpine
      volumes:
        - data_postgres:/var/lib/postgresql/data/
      env_file:
        - envs/.env
      expose:
        - 5432
      ports:
        - 5432:5432

volumes:
  data_postgres: