version: '3'
services:
    auth:
      build: src
      depends_on:
        - redis
        - postgres
      volumes:
        - ./src:/auth
      expose:
        - 5000
      ports:
        - '5555:5555'

    redis:
      image: redis:7-alpine
      ports:
        - 6379:6379

    postgres:
      image: postgres:13.0-alpine
      volumes:
        - data_postgres:/var/lib/postgresql/data/
      env_file:
        - envs/.env
      expose:
        - 5432
      ports:
        - 5432:5432

volumes:
  data_postgres: