version: '3'
services:
    auth:
      build: src
      container_name: auth
      env_file:
        - envs/.env
      depends_on:
        - redis_auth
        - postgres_auth
      volumes:
        - ./src:/auth
        - ./src/migrations:/auth/migrations
      expose:
        - 5000

    redis_auth:
      image: redis:7-alpine
      expose:
        - 6379

    postgres_auth:
      image: postgres:13.0-alpine
      volumes:
        - data_postgres:/var/lib/postgresql/data/
      env_file:
        - envs/.env
      expose:
        - 5432

    nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
      depends_on:
        - auth
      ports:
        - "80:80"

    jaeger:
      image: jaegertracing/all-in-one:latest
      ports:
        - "6831:6831/udp"
        - "16686:16686"
      environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411

volumes:
  data_postgres: