"""empty message

Revision ID: 15abbf5ba2d0
Revises: dd1ff5cdd47a
Create Date: 2023-03-02 20:41:48.686551

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "15abbf5ba2d0"
down_revision = "dd1ff5cdd47a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
