"""Cascade deleting history and social accounts

Revision ID: b2b05c7467bf
Revises: ef86a676f822
Create Date: 2023-03-13 17:07:29.986040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2b05c7467bf'
down_revision = 'ef86a676f822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_user_id_fkey', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('history_auth', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('history_auth_id_date_auth_key', 'history_auth', type_='unique')
    op.drop_constraint('history_auth_user_id_fkey', 'history_auth', type_='foreignkey')
    op.create_foreign_key(None, 'history_auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'social_account', ['id'])
    op.drop_constraint('social_account_user_id_fkey', 'social_account', type_='foreignkey')
    op.create_foreign_key(None, 'social_account', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_account', type_='foreignkey')
    op.create_foreign_key('social_account_user_id_fkey', 'social_account', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'social_account', type_='unique')
    op.drop_constraint(None, 'history_auth', type_='foreignkey')
    op.create_foreign_key('history_auth_user_id_fkey', 'history_auth', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'history_auth', type_='unique')
    op.create_unique_constraint('history_auth_id_date_auth_key', 'history_auth', ['id', 'date_auth'])
    op.alter_column('history_auth', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key('device_user_id_fkey', 'device', 'users', ['user_id'], ['id'])
    op.create_table('history_auth_2023_05',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_05_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_05_id_date_auth_key')
    )
    op.create_table('history_auth_2023_02',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_02_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_02_id_date_auth_key')
    )
    op.create_table('history_auth_2023_01',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_01_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_01_id_date_auth_key')
    )
    op.create_table('history_auth_2023_11',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_11_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_11_id_date_auth_key')
    )
    op.create_table('history_auth_2023_04',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_04_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_04_id_date_auth_key')
    )
    op.create_table('history_auth_2023_09',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_09_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_09_id_date_auth_key')
    )
    op.create_table('history_auth_2023_12',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_12_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_12_id_date_auth_key')
    )
    op.create_table('history_auth_2023_08',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_08_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_08_id_date_auth_key')
    )
    op.create_table('history_auth_2023_07',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_07_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_07_id_date_auth_key')
    )
    op.create_table('history_auth_2023_03',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_03_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_03_id_date_auth_key')
    )
    op.create_table('history_auth_2023_06',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_06_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_06_id_date_auth_key')
    )
    op.create_table('history_auth_2023_10',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_auth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='history_auth_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'date_auth', name='history_auth_2023_10_pkey'),
    sa.UniqueConstraint('id', 'date_auth', name='history_auth_2023_10_id_date_auth_key')
    )
    # ### end Alembic commands ###
