"""empty message

Revision ID: dd1ff5cdd47a
Revises: ef86a676f822
Create Date: 2023-03-02 20:34:33.583756

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "dd1ff5cdd47a"
down_revision = "ef86a676f822"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "social_account", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "social_account", type_="unique")
    # ### end Alembic commands ###
