"""Create table social accounts

Revision ID: ef86a676f822
Revises: af07ce690082
Create Date: 2023-03-02 20:21:38.505690

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ef86a676f822"
down_revision = "af07ce690082"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_account",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("social_id", sa.Text(), nullable=False),
        sa.Column("social_name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id",  name="social_account_pkey"),
        sa.UniqueConstraint("social_id", "social_name", name="social_pk"),
    )
    op.create_unique_constraint(None, "device", ["id"])
    op.create_unique_constraint(None, "history_auth", ["id", "date_auth"])
    op.create_unique_constraint(None, "permissions", ["id"])
    op.create_unique_constraint(None, "roles", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "roles", type_="unique")
    op.drop_constraint(None, "permissions", type_="unique")
    op.drop_constraint(None, "history_auth", type_="unique")
    op.drop_constraint(None, "device", type_="unique")
    op.drop_table("social_account")
    # ### end Alembic commands ###
