import datetime

CACHE_REFRESH_TOKEN_EXPIRATION_TIME = 15 * 60
CACHE_ACCESS_TOKEN_EXPERATION_TIME = 10 * 24 * 60 * 60
REFRESH_TOKEN_EXPIRATION_TIMEDELTA = datetime.timedelta(
    CACHE_REFRESH_TOKEN_EXPIRATION_TIME
)
ACCESS_TOKEN_EXPERATION_TIMEDELTA = datetime.timedelta(
    CACHE_ACCESS_TOKEN_EXPERATION_TIME
)
